name: Build and Test Docker Container

on:
  push:
    branches:
      - main
      - dev
      - build/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ohthepain
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ohthepain/config-server:latest
        build-args: |
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Run tests
      run: docker run -e "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" -e "TEST_ADMIN_PASSWORD=${{ secrets.TEST_ADMIN_PASSWORD }}" -e "DATABASE_URL=postgresql://postgres:fuqjUk-zadmat-6hungu@yogadb.c0gkoazda8iy.eu-central-1.rds.amazonaws.com:5432/yogadb?schema=public&connect_timeout=30" --rm ohthepain/config-server:latest npm run test
