name: Migrate DB and Run Jest Tests

on:
  push:
    branches:
      - main
      - dev
      - build/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    # - name: Run migrations
    #   env:
    #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #   run:
    #     npx prisma migrate dev
    - name: Run Jest tests
      run: npm test
      env: 
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
